version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Smart123!
      - MSSQL_SA_PASSWORD=Smart123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - app-sql-data:/var/opt/mssql

  procesiowebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
volumes:
  app-sql-data:
    external: false